// Package api_docs Code generated by swaggo/swag. DO NOT EDIT
package api_docs

import "github.com/swaggo/swag"

const docTemplate = `{
    "schemes": {{ marshal .Schemes }},
    "swagger": "2.0",
    "info": {
        "description": "{{escape .Description}}",
        "title": "{{.Title}}",
        "termsOfService": "http://swagger.io/terms/",
        "contact": {
            "name": "API Support",
            "url": "http://www.swagger.io/support",
            "email": "support@swagger.io"
        },
        "license": {
            "name": "Apache 2.0",
            "url": "http://www.apache.org/licenses/LICENSE-2.0.html"
        },
        "version": "{{.Version}}"
    },
    "host": "{{.Host}}",
    "basePath": "{{.BasePath}}",
    "paths": {
        "/auth/change-password": {
            "post": {
                "security": [
                    {
                        "BearerAuth": []
                    }
                ],
                "description": "修改当前用户的密码",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "用户认证"
                ],
                "summary": "修改密码",
                "parameters": [
                    {
                        "description": "密码修改信息",
                        "name": "request",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/models.ChangePasswordRequest"
                        }
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/models.APIResponse"
                        }
                    },
                    "400": {
                        "description": "Bad Request",
                        "schema": {
                            "$ref": "#/definitions/models.APIResponse"
                        }
                    },
                    "401": {
                        "description": "Unauthorized",
                        "schema": {
                            "$ref": "#/definitions/models.APIResponse"
                        }
                    }
                }
            }
        },
        "/auth/login": {
            "post": {
                "description": "用户登录获取访问令牌",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "用户认证"
                ],
                "summary": "用户登录",
                "parameters": [
                    {
                        "description": "登录信息",
                        "name": "request",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/models.LoginRequest"
                        }
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "allOf": [
                                {
                                    "$ref": "#/definitions/models.APIResponse"
                                },
                                {
                                    "type": "object",
                                    "properties": {
                                        "data": {
                                            "$ref": "#/definitions/models.LoginResponse"
                                        }
                                    }
                                }
                            ]
                        }
                    },
                    "400": {
                        "description": "Bad Request",
                        "schema": {
                            "$ref": "#/definitions/models.APIResponse"
                        }
                    },
                    "401": {
                        "description": "Unauthorized",
                        "schema": {
                            "$ref": "#/definitions/models.APIResponse"
                        }
                    }
                }
            }
        },
        "/auth/profile": {
            "get": {
                "security": [
                    {
                        "BearerAuth": []
                    }
                ],
                "description": "获取当前登录用户的资料信息",
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "用户认证"
                ],
                "summary": "获取用户资料",
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "allOf": [
                                {
                                    "$ref": "#/definitions/models.APIResponse"
                                },
                                {
                                    "type": "object",
                                    "properties": {
                                        "data": {
                                            "$ref": "#/definitions/models.UserProfile"
                                        }
                                    }
                                }
                            ]
                        }
                    },
                    "401": {
                        "description": "Unauthorized",
                        "schema": {
                            "$ref": "#/definitions/models.APIResponse"
                        }
                    },
                    "500": {
                        "description": "Internal Server Error",
                        "schema": {
                            "$ref": "#/definitions/models.APIResponse"
                        }
                    }
                }
            }
        },
        "/auth/register": {
            "post": {
                "description": "注册新用户账户",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "用户认证"
                ],
                "summary": "用户注册",
                "parameters": [
                    {
                        "description": "注册信息",
                        "name": "request",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/models.RegisterRequest"
                        }
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "allOf": [
                                {
                                    "$ref": "#/definitions/models.APIResponse"
                                },
                                {
                                    "type": "object",
                                    "properties": {
                                        "data": {
                                            "$ref": "#/definitions/models.UserProfile"
                                        }
                                    }
                                }
                            ]
                        }
                    },
                    "400": {
                        "description": "Bad Request",
                        "schema": {
                            "$ref": "#/definitions/models.APIResponse"
                        }
                    },
                    "500": {
                        "description": "Internal Server Error",
                        "schema": {
                            "$ref": "#/definitions/models.APIResponse"
                        }
                    }
                }
            }
        },
        "/cleanup/{taskId}": {
            "delete": {
                "description": "清理任务相关的所有文件",
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "任务管理"
                ],
                "summary": "清理任务文件",
                "parameters": [
                    {
                        "type": "string",
                        "description": "任务ID",
                        "name": "taskId",
                        "in": "path",
                        "required": true
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "allOf": [
                                {
                                    "$ref": "#/definitions/models.APIResponse"
                                },
                                {
                                    "type": "object",
                                    "properties": {
                                        "data": {
                                            "$ref": "#/definitions/models.CleanupResponse"
                                        }
                                    }
                                }
                            ]
                        }
                    },
                    "404": {
                        "description": "Not Found",
                        "schema": {
                            "$ref": "#/definitions/models.APIResponse"
                        }
                    },
                    "500": {
                        "description": "Internal Server Error",
                        "schema": {
                            "$ref": "#/definitions/models.APIResponse"
                        }
                    }
                }
            }
        },
        "/convert": {
            "post": {
                "description": "开始将txt文件转换为电子书",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "转换管理"
                ],
                "summary": "开始电子书转换",
                "parameters": [
                    {
                        "description": "转换参数",
                        "name": "request",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/models.ConvertRequest"
                        }
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "allOf": [
                                {
                                    "$ref": "#/definitions/models.APIResponse"
                                },
                                {
                                    "type": "object",
                                    "properties": {
                                        "data": {
                                            "$ref": "#/definitions/models.ConvertResponse"
                                        }
                                    }
                                }
                            ]
                        }
                    },
                    "400": {
                        "description": "Bad Request",
                        "schema": {
                            "$ref": "#/definitions/models.APIResponse"
                        }
                    },
                    "500": {
                        "description": "Internal Server Error",
                        "schema": {
                            "$ref": "#/definitions/models.APIResponse"
                        }
                    }
                }
            }
        },
        "/convert/batch": {
            "post": {
                "security": [
                    {
                        "BearerAuth": []
                    }
                ],
                "description": "批量转换多个文件",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "批量转换"
                ],
                "summary": "批量转换",
                "parameters": [
                    {
                        "description": "批量转换请求",
                        "name": "request",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/models.BatchConversionRequest"
                        }
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "allOf": [
                                {
                                    "$ref": "#/definitions/models.APIResponse"
                                },
                                {
                                    "type": "object",
                                    "properties": {
                                        "data": {
                                            "$ref": "#/definitions/models.BatchConversionResponse"
                                        }
                                    }
                                }
                            ]
                        }
                    },
                    "400": {
                        "description": "Bad Request",
                        "schema": {
                            "$ref": "#/definitions/models.APIResponse"
                        }
                    },
                    "401": {
                        "description": "Unauthorized",
                        "schema": {
                            "$ref": "#/definitions/models.APIResponse"
                        }
                    },
                    "500": {
                        "description": "Internal Server Error",
                        "schema": {
                            "$ref": "#/definitions/models.APIResponse"
                        }
                    }
                }
            }
        },
        "/download/{fileId}": {
            "get": {
                "description": "下载转换后的电子书文件",
                "produces": [
                    "application/octet-stream"
                ],
                "tags": [
                    "文件管理"
                ],
                "summary": "下载电子书文件",
                "parameters": [
                    {
                        "type": "string",
                        "description": "文件ID",
                        "name": "fileId",
                        "in": "path",
                        "required": true
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "type": "file"
                        }
                    },
                    "404": {
                        "description": "Not Found",
                        "schema": {
                            "$ref": "#/definitions/models.APIResponse"
                        }
                    },
                    "500": {
                        "description": "Internal Server Error",
                        "schema": {
                            "$ref": "#/definitions/models.APIResponse"
                        }
                    }
                }
            }
        },
        "/events/{taskId}": {
            "get": {
                "description": "通过SSE获取任务的实时事件流",
                "produces": [
                    "text/event-stream"
                ],
                "tags": [
                    "转换管理"
                ],
                "summary": "获取任务事件流",
                "parameters": [
                    {
                        "type": "string",
                        "description": "任务ID",
                        "name": "taskId",
                        "in": "path",
                        "required": true
                    }
                ],
                "responses": {
                    "200": {
                        "description": "SSE事件流",
                        "schema": {
                            "type": "string"
                        }
                    },
                    "404": {
                        "description": "Not Found",
                        "schema": {
                            "$ref": "#/definitions/models.APIResponse"
                        }
                    }
                }
            }
        },
        "/history": {
            "get": {
                "security": [
                    {
                        "BearerAuth": []
                    }
                ],
                "description": "获取当前用户的转换历史记录列表",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "转换历史"
                ],
                "summary": "获取转换历史列表",
                "parameters": [
                    {
                        "type": "integer",
                        "default": 1,
                        "description": "页码",
                        "name": "page",
                        "in": "query"
                    },
                    {
                        "type": "integer",
                        "default": 20,
                        "description": "每页数量",
                        "name": "page_size",
                        "in": "query"
                    },
                    {
                        "type": "string",
                        "description": "状态过滤",
                        "name": "status",
                        "in": "query"
                    },
                    {
                        "type": "string",
                        "description": "格式过滤",
                        "name": "format",
                        "in": "query"
                    },
                    {
                        "type": "string",
                        "description": "开始日期",
                        "name": "start_date",
                        "in": "query"
                    },
                    {
                        "type": "string",
                        "description": "结束日期",
                        "name": "end_date",
                        "in": "query"
                    },
                    {
                        "type": "string",
                        "description": "关键词搜索",
                        "name": "keyword",
                        "in": "query"
                    },
                    {
                        "type": "string",
                        "default": "created_at",
                        "description": "排序字段",
                        "name": "sort_by",
                        "in": "query"
                    },
                    {
                        "type": "string",
                        "default": "desc",
                        "description": "排序方向",
                        "name": "sort_order",
                        "in": "query"
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "allOf": [
                                {
                                    "$ref": "#/definitions/models.APIResponse"
                                },
                                {
                                    "type": "object",
                                    "properties": {
                                        "data": {
                                            "$ref": "#/definitions/models.HistoryListResponse"
                                        }
                                    }
                                }
                            ]
                        }
                    },
                    "401": {
                        "description": "Unauthorized",
                        "schema": {
                            "$ref": "#/definitions/models.APIResponse"
                        }
                    },
                    "500": {
                        "description": "Internal Server Error",
                        "schema": {
                            "$ref": "#/definitions/models.APIResponse"
                        }
                    }
                }
            }
        },
        "/history/stats": {
            "get": {
                "security": [
                    {
                        "BearerAuth": []
                    }
                ],
                "description": "获取当前用户的转换统计信息",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "转换历史"
                ],
                "summary": "获取转换统计信息",
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "allOf": [
                                {
                                    "$ref": "#/definitions/models.APIResponse"
                                },
                                {
                                    "type": "object",
                                    "properties": {
                                        "data": {
                                            "$ref": "#/definitions/models.HistoryStatsResponse"
                                        }
                                    }
                                }
                            ]
                        }
                    },
                    "401": {
                        "description": "Unauthorized",
                        "schema": {
                            "$ref": "#/definitions/models.APIResponse"
                        }
                    },
                    "500": {
                        "description": "Internal Server Error",
                        "schema": {
                            "$ref": "#/definitions/models.APIResponse"
                        }
                    }
                }
            }
        },
        "/history/{id}": {
            "delete": {
                "security": [
                    {
                        "BearerAuth": []
                    }
                ],
                "description": "删除指定的转换历史记录",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "转换历史"
                ],
                "summary": "删除转换历史",
                "parameters": [
                    {
                        "type": "integer",
                        "description": "历史记录ID",
                        "name": "id",
                        "in": "path",
                        "required": true
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/models.APIResponse"
                        }
                    },
                    "400": {
                        "description": "Bad Request",
                        "schema": {
                            "$ref": "#/definitions/models.APIResponse"
                        }
                    },
                    "401": {
                        "description": "Unauthorized",
                        "schema": {
                            "$ref": "#/definitions/models.APIResponse"
                        }
                    },
                    "500": {
                        "description": "Internal Server Error",
                        "schema": {
                            "$ref": "#/definitions/models.APIResponse"
                        }
                    }
                }
            }
        },
        "/presets": {
            "get": {
                "security": [
                    {
                        "BearerAuth": []
                    }
                ],
                "description": "获取当前用户的转换预设列表",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "转换预设"
                ],
                "summary": "获取转换预设列表",
                "parameters": [
                    {
                        "type": "integer",
                        "default": 1,
                        "description": "页码",
                        "name": "page",
                        "in": "query"
                    },
                    {
                        "type": "integer",
                        "default": 20,
                        "description": "每页数量",
                        "name": "page_size",
                        "in": "query"
                    },
                    {
                        "type": "string",
                        "description": "格式过滤",
                        "name": "format",
                        "in": "query"
                    },
                    {
                        "type": "string",
                        "description": "关键词搜索",
                        "name": "keyword",
                        "in": "query"
                    },
                    {
                        "type": "boolean",
                        "description": "是否公开",
                        "name": "is_public",
                        "in": "query"
                    },
                    {
                        "type": "string",
                        "default": "created_at",
                        "description": "排序字段",
                        "name": "sort_by",
                        "in": "query"
                    },
                    {
                        "type": "string",
                        "default": "desc",
                        "description": "排序方向",
                        "name": "sort_order",
                        "in": "query"
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "allOf": [
                                {
                                    "$ref": "#/definitions/models.APIResponse"
                                },
                                {
                                    "type": "object",
                                    "properties": {
                                        "data": {
                                            "type": "array",
                                            "items": {
                                                "$ref": "#/definitions/models.ConversionPreset"
                                            }
                                        }
                                    }
                                }
                            ]
                        }
                    },
                    "401": {
                        "description": "Unauthorized",
                        "schema": {
                            "$ref": "#/definitions/models.APIResponse"
                        }
                    },
                    "500": {
                        "description": "Internal Server Error",
                        "schema": {
                            "$ref": "#/definitions/models.APIResponse"
                        }
                    }
                }
            },
            "post": {
                "security": [
                    {
                        "BearerAuth": []
                    }
                ],
                "description": "创建新的转换预设配置",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "转换预设"
                ],
                "summary": "创建转换预设",
                "parameters": [
                    {
                        "description": "预设信息",
                        "name": "request",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/models.PresetCreateRequest"
                        }
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "allOf": [
                                {
                                    "$ref": "#/definitions/models.APIResponse"
                                },
                                {
                                    "type": "object",
                                    "properties": {
                                        "data": {
                                            "$ref": "#/definitions/models.ConversionPreset"
                                        }
                                    }
                                }
                            ]
                        }
                    },
                    "400": {
                        "description": "Bad Request",
                        "schema": {
                            "$ref": "#/definitions/models.APIResponse"
                        }
                    },
                    "401": {
                        "description": "Unauthorized",
                        "schema": {
                            "$ref": "#/definitions/models.APIResponse"
                        }
                    },
                    "500": {
                        "description": "Internal Server Error",
                        "schema": {
                            "$ref": "#/definitions/models.APIResponse"
                        }
                    }
                }
            }
        },
        "/presets/{id}": {
            "put": {
                "security": [
                    {
                        "BearerAuth": []
                    }
                ],
                "description": "更新指定的转换预设配置",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "转换预设"
                ],
                "summary": "更新转换预设",
                "parameters": [
                    {
                        "type": "integer",
                        "description": "预设ID",
                        "name": "id",
                        "in": "path",
                        "required": true
                    },
                    {
                        "description": "预设信息",
                        "name": "request",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/models.PresetUpdateRequest"
                        }
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/models.APIResponse"
                        }
                    },
                    "400": {
                        "description": "Bad Request",
                        "schema": {
                            "$ref": "#/definitions/models.APIResponse"
                        }
                    },
                    "401": {
                        "description": "Unauthorized",
                        "schema": {
                            "$ref": "#/definitions/models.APIResponse"
                        }
                    },
                    "500": {
                        "description": "Internal Server Error",
                        "schema": {
                            "$ref": "#/definitions/models.APIResponse"
                        }
                    }
                }
            },
            "delete": {
                "security": [
                    {
                        "BearerAuth": []
                    }
                ],
                "description": "删除指定的转换预设",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "转换预设"
                ],
                "summary": "删除转换预设",
                "parameters": [
                    {
                        "type": "integer",
                        "description": "预设ID",
                        "name": "id",
                        "in": "path",
                        "required": true
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/models.APIResponse"
                        }
                    },
                    "400": {
                        "description": "Bad Request",
                        "schema": {
                            "$ref": "#/definitions/models.APIResponse"
                        }
                    },
                    "401": {
                        "description": "Unauthorized",
                        "schema": {
                            "$ref": "#/definitions/models.APIResponse"
                        }
                    },
                    "500": {
                        "description": "Internal Server Error",
                        "schema": {
                            "$ref": "#/definitions/models.APIResponse"
                        }
                    }
                }
            }
        },
        "/status/{taskId}": {
            "get": {
                "description": "查询转换任务的当前状态",
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "转换管理"
                ],
                "summary": "查询转换状态",
                "parameters": [
                    {
                        "type": "string",
                        "description": "任务ID",
                        "name": "taskId",
                        "in": "path",
                        "required": true
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "allOf": [
                                {
                                    "$ref": "#/definitions/models.APIResponse"
                                },
                                {
                                    "type": "object",
                                    "properties": {
                                        "data": {
                                            "$ref": "#/definitions/models.TaskStatusResponse"
                                        }
                                    }
                                }
                            ]
                        }
                    },
                    "404": {
                        "description": "Not Found",
                        "schema": {
                            "$ref": "#/definitions/models.APIResponse"
                        }
                    },
                    "500": {
                        "description": "Internal Server Error",
                        "schema": {
                            "$ref": "#/definitions/models.APIResponse"
                        }
                    }
                }
            }
        },
        "/upload": {
            "post": {
                "description": "上传txt文件用于转换",
                "consumes": [
                    "multipart/form-data"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "文件管理"
                ],
                "summary": "上传txt文件",
                "parameters": [
                    {
                        "type": "file",
                        "description": "txt文件",
                        "name": "file",
                        "in": "formData",
                        "required": true
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "allOf": [
                                {
                                    "$ref": "#/definitions/models.APIResponse"
                                },
                                {
                                    "type": "object",
                                    "properties": {
                                        "data": {
                                            "$ref": "#/definitions/models.UploadResponse"
                                        }
                                    }
                                }
                            ]
                        }
                    },
                    "400": {
                        "description": "Bad Request",
                        "schema": {
                            "$ref": "#/definitions/models.APIResponse"
                        }
                    },
                    "500": {
                        "description": "Internal Server Error",
                        "schema": {
                            "$ref": "#/definitions/models.APIResponse"
                        }
                    }
                }
            }
        }
    },
    "definitions": {
        "models.APIResponse": {
            "type": "object",
            "properties": {
                "code": {
                    "description": "状态码",
                    "type": "integer",
                    "example": 200
                },
                "data": {
                    "description": "数据"
                },
                "error": {
                    "description": "错误信息",
                    "type": "string",
                    "example": ""
                },
                "message": {
                    "description": "消息",
                    "type": "string",
                    "example": "success"
                }
            }
        },
        "models.BatchConversionRequest": {
            "type": "object",
            "required": [
                "files",
                "output_format"
            ],
            "properties": {
                "author": {
                    "type": "string"
                },
                "book_title": {
                    "type": "string"
                },
                "common_options": {
                    "type": "object",
                    "additionalProperties": true
                },
                "files": {
                    "type": "array",
                    "maxItems": 10,
                    "minItems": 1,
                    "items": {
                        "$ref": "#/definitions/models.BatchFileInfo"
                    }
                },
                "output_format": {
                    "type": "string",
                    "enum": [
                        "epub",
                        "mobi",
                        "azw3",
                        "pdf"
                    ]
                }
            }
        },
        "models.BatchConversionResponse": {
            "type": "object",
            "properties": {
                "batch_id": {
                    "type": "string"
                },
                "created_at": {
                    "type": "string"
                },
                "status": {
                    "type": "string"
                },
                "tasks": {
                    "type": "array",
                    "items": {
                        "$ref": "#/definitions/models.BatchTaskInfo"
                    }
                },
                "total_files": {
                    "type": "integer"
                }
            }
        },
        "models.BatchFileInfo": {
            "type": "object",
            "required": [
                "file_name",
                "file_size"
            ],
            "properties": {
                "custom_options": {
                    "type": "object",
                    "additionalProperties": true
                },
                "file_hash": {
                    "type": "string"
                },
                "file_name": {
                    "type": "string"
                },
                "file_size": {
                    "type": "integer",
                    "minimum": 1
                }
            }
        },
        "models.BatchTaskInfo": {
            "type": "object",
            "properties": {
                "error_message": {
                    "type": "string"
                },
                "file_name": {
                    "type": "string"
                },
                "status": {
                    "type": "string"
                },
                "task_id": {
                    "type": "string"
                }
            }
        },
        "models.ChangePasswordRequest": {
            "type": "object",
            "required": [
                "new_password",
                "old_password"
            ],
            "properties": {
                "new_password": {
                    "type": "string",
                    "minLength": 6
                },
                "old_password": {
                    "type": "string"
                }
            }
        },
        "models.CleanupResponse": {
            "type": "object",
            "properties": {
                "cleaned": {
                    "description": "是否清理成功",
                    "type": "boolean",
                    "example": true
                },
                "cleaned_at": {
                    "description": "清理时间",
                    "type": "string",
                    "example": "2024-01-01T00:10:00Z"
                },
                "cleaned_files": {
                    "description": "已清理的文件列表",
                    "type": "array",
                    "items": {
                        "type": "string"
                    }
                },
                "message": {
                    "description": "消息",
                    "type": "string",
                    "example": "清理完成"
                },
                "task_id": {
                    "description": "任务ID",
                    "type": "string",
                    "example": "task_123456789"
                }
            }
        },
        "models.ConversionHistory": {
            "type": "object",
            "properties": {
                "convert_options": {
                    "$ref": "#/definitions/models.ConvertOptionsJSON"
                },
                "created_at": {
                    "type": "string"
                },
                "download_count": {
                    "type": "integer"
                },
                "duration": {
                    "description": "转换耗时（毫秒）",
                    "type": "integer"
                },
                "end_time": {
                    "type": "string"
                },
                "error_message": {
                    "type": "string"
                },
                "id": {
                    "type": "integer"
                },
                "is_deleted": {
                    "type": "boolean"
                },
                "last_download_at": {
                    "type": "string"
                },
                "original_file_hash": {
                    "type": "string"
                },
                "original_file_name": {
                    "type": "string"
                },
                "original_file_size": {
                    "type": "integer"
                },
                "output_file_name": {
                    "type": "string"
                },
                "output_file_size": {
                    "type": "integer"
                },
                "output_format": {
                    "type": "string"
                },
                "start_time": {
                    "type": "string"
                },
                "status": {
                    "type": "string"
                },
                "task_id": {
                    "type": "string"
                },
                "updated_at": {
                    "type": "string"
                },
                "user": {
                    "description": "关联",
                    "allOf": [
                        {
                            "$ref": "#/definitions/models.User"
                        }
                    ]
                },
                "user_id": {
                    "type": "integer"
                }
            }
        },
        "models.ConversionPreset": {
            "type": "object",
            "properties": {
                "created_at": {
                    "type": "string"
                },
                "description": {
                    "type": "string"
                },
                "id": {
                    "type": "integer"
                },
                "is_default": {
                    "type": "boolean"
                },
                "is_public": {
                    "type": "boolean"
                },
                "name": {
                    "type": "string"
                },
                "options": {
                    "$ref": "#/definitions/models.ConvertOptionsJSON"
                },
                "output_format": {
                    "type": "string"
                },
                "updated_at": {
                    "type": "string"
                },
                "usage_count": {
                    "type": "integer"
                },
                "user": {
                    "description": "关联",
                    "allOf": [
                        {
                            "$ref": "#/definitions/models.User"
                        }
                    ]
                },
                "user_id": {
                    "type": "integer"
                }
            }
        },
        "models.ConvertOptionsJSON": {
            "type": "object",
            "additionalProperties": true
        },
        "models.ConvertRequest": {
            "type": "object",
            "required": [
                "bookname",
                "format",
                "task_id"
            ],
            "properties": {
                "align": {
                    "description": "标题对齐方式",
                    "type": "string",
                    "example": "center"
                },
                "author": {
                    "description": "作者",
                    "type": "string",
                    "example": "作者名"
                },
                "bookname": {
                    "description": "书名",
                    "type": "string",
                    "example": "示例小说"
                },
                "bottom": {
                    "description": "段落间距",
                    "type": "string",
                    "example": "1em"
                },
                "cover": {
                    "description": "封面设置",
                    "type": "string",
                    "example": "gen"
                },
                "cover_orly_color": {
                    "description": "封面颜色",
                    "type": "string",
                    "example": "#FF6B6B"
                },
                "cover_orly_idx": {
                    "description": "封面动物索引",
                    "type": "integer",
                    "example": 1
                },
                "exclusion_pattern": {
                    "description": "排除规则",
                    "type": "string",
                    "example": "^第[0-9一二三四五六七八九十零〇百千两 ]+(部门|部队)"
                },
                "font": {
                    "description": "嵌入字体",
                    "type": "string",
                    "example": ""
                },
                "format": {
                    "description": "输出格式",
                    "type": "string",
                    "enum": [
                        "epub",
                        "mobi",
                        "azw3",
                        "all"
                    ],
                    "example": "epub"
                },
                "indent": {
                    "description": "段落缩进",
                    "type": "integer",
                    "example": 2
                },
                "lang": {
                    "description": "语言设置",
                    "type": "string",
                    "example": "zh"
                },
                "line_height": {
                    "description": "行高",
                    "type": "string",
                    "example": "1.5"
                },
                "match": {
                    "description": "章节匹配规则",
                    "type": "string",
                    "example": "^第[0-9一二三四五六七八九十零〇百千两 ]+[章回节集幕卷部]"
                },
                "max": {
                    "description": "标题最大字数",
                    "type": "integer",
                    "example": 35
                },
                "task_id": {
                    "description": "任务ID",
                    "type": "string",
                    "example": "task_123456789"
                },
                "tips": {
                    "description": "是否添加教程文本",
                    "type": "boolean",
                    "example": true
                },
                "unknow_title": {
                    "description": "未知章节名称",
                    "type": "string",
                    "example": "章节正文"
                },
                "volume_match": {
                    "description": "卷匹配规则",
                    "type": "string",
                    "example": "^第[0-9一二三四五六七八九十零〇百千两 ]+[卷部]"
                }
            }
        },
        "models.ConvertResponse": {
            "type": "object",
            "properties": {
                "message": {
                    "description": "消息",
                    "type": "string",
                    "example": "转换任务已开始"
                },
                "started_at": {
                    "description": "开始时间",
                    "type": "string",
                    "example": "2024-01-01T00:00:00Z"
                },
                "status": {
                    "description": "状态",
                    "type": "string",
                    "example": "processing"
                },
                "task_id": {
                    "description": "任务ID",
                    "type": "string",
                    "example": "task_123456789"
                }
            }
        },
        "models.ConvertedFile": {
            "type": "object",
            "properties": {
                "file_id": {
                    "description": "文件ID",
                    "type": "string",
                    "example": "file_123456789"
                },
                "filename": {
                    "description": "文件名",
                    "type": "string",
                    "example": "example.epub"
                },
                "format": {
                    "description": "格式",
                    "type": "string",
                    "example": "epub"
                },
                "path": {
                    "description": "文件路径(内部使用)",
                    "type": "string"
                },
                "size": {
                    "description": "文件大小(字节)",
                    "type": "integer",
                    "example": 2048000
                }
            }
        },
        "models.HistoryListResponse": {
            "type": "object",
            "properties": {
                "items": {
                    "type": "array",
                    "items": {
                        "$ref": "#/definitions/models.ConversionHistory"
                    }
                },
                "page": {
                    "type": "integer"
                },
                "page_size": {
                    "type": "integer"
                },
                "total": {
                    "type": "integer"
                },
                "total_pages": {
                    "type": "integer"
                }
            }
        },
        "models.HistoryStatsResponse": {
            "type": "object",
            "properties": {
                "average_duration": {
                    "type": "number"
                },
                "failed_conversions": {
                    "type": "integer"
                },
                "format_stats": {
                    "type": "object",
                    "additionalProperties": {
                        "type": "integer",
                        "format": "int64"
                    }
                },
                "monthly_stats": {
                    "type": "array",
                    "items": {
                        "$ref": "#/definitions/models.MonthlyStats"
                    }
                },
                "recent_activity": {
                    "type": "array",
                    "items": {
                        "$ref": "#/definitions/models.ConversionHistory"
                    }
                },
                "success_rate": {
                    "type": "number"
                },
                "successful_conversions": {
                    "type": "integer"
                },
                "total_conversions": {
                    "type": "integer"
                },
                "total_file_size": {
                    "type": "integer"
                }
            }
        },
        "models.LoginRequest": {
            "type": "object",
            "required": [
                "password",
                "username"
            ],
            "properties": {
                "password": {
                    "type": "string",
                    "example": "password123"
                },
                "username": {
                    "type": "string",
                    "example": "admin"
                }
            }
        },
        "models.LoginResponse": {
            "type": "object",
            "properties": {
                "expires_at": {
                    "type": "string",
                    "example": "2024-01-01T12:00:00Z"
                },
                "token": {
                    "type": "string",
                    "example": "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9..."
                },
                "user": {
                    "$ref": "#/definitions/models.User"
                }
            }
        },
        "models.MonthlyStats": {
            "type": "object",
            "properties": {
                "count": {
                    "type": "integer"
                },
                "failure_count": {
                    "type": "integer"
                },
                "month": {
                    "type": "string"
                },
                "success_count": {
                    "type": "integer"
                },
                "year": {
                    "type": "integer"
                }
            }
        },
        "models.PresetCreateRequest": {
            "type": "object",
            "required": [
                "name",
                "output_format"
            ],
            "properties": {
                "description": {
                    "type": "string",
                    "maxLength": 500
                },
                "is_default": {
                    "type": "boolean"
                },
                "is_public": {
                    "type": "boolean"
                },
                "name": {
                    "type": "string",
                    "maxLength": 100,
                    "minLength": 1
                },
                "options": {
                    "type": "object",
                    "additionalProperties": true
                },
                "output_format": {
                    "type": "string",
                    "enum": [
                        "epub",
                        "mobi",
                        "azw3",
                        "pdf"
                    ]
                }
            }
        },
        "models.PresetUpdateRequest": {
            "type": "object",
            "properties": {
                "description": {
                    "type": "string",
                    "maxLength": 500
                },
                "is_default": {
                    "type": "boolean"
                },
                "is_public": {
                    "type": "boolean"
                },
                "name": {
                    "type": "string",
                    "maxLength": 100,
                    "minLength": 1
                },
                "options": {
                    "type": "object",
                    "additionalProperties": true
                },
                "output_format": {
                    "type": "string",
                    "enum": [
                        "epub",
                        "mobi",
                        "azw3",
                        "pdf"
                    ]
                }
            }
        },
        "models.RegisterRequest": {
            "type": "object",
            "required": [
                "email",
                "password",
                "username"
            ],
            "properties": {
                "email": {
                    "type": "string",
                    "example": "user@example.com"
                },
                "password": {
                    "type": "string",
                    "minLength": 6,
                    "example": "password123"
                },
                "username": {
                    "type": "string",
                    "maxLength": 20,
                    "minLength": 3,
                    "example": "newuser"
                }
            }
        },
        "models.TaskStatusResponse": {
            "type": "object",
            "properties": {
                "completed_at": {
                    "description": "完成时间",
                    "type": "string",
                    "example": "2024-01-01T00:05:00Z"
                },
                "error": {
                    "description": "错误信息",
                    "type": "string",
                    "example": ""
                },
                "files": {
                    "description": "转换后的文件列表",
                    "type": "array",
                    "items": {
                        "$ref": "#/definitions/models.ConvertedFile"
                    }
                },
                "logs": {
                    "description": "处理日志",
                    "type": "array",
                    "items": {
                        "type": "string"
                    }
                },
                "message": {
                    "description": "当前状态消息",
                    "type": "string",
                    "example": "转换完成"
                },
                "metadata": {
                    "description": "元数据",
                    "type": "object",
                    "additionalProperties": true
                },
                "progress": {
                    "description": "进度百分比",
                    "type": "integer",
                    "example": 100
                },
                "started_at": {
                    "description": "开始时间",
                    "type": "string",
                    "example": "2024-01-01T00:00:00Z"
                },
                "status": {
                    "description": "状态",
                    "type": "string",
                    "example": "completed"
                },
                "task_id": {
                    "description": "任务ID",
                    "type": "string",
                    "example": "task_123456789"
                }
            }
        },
        "models.UploadResponse": {
            "type": "object",
            "properties": {
                "filename": {
                    "description": "文件名",
                    "type": "string",
                    "example": "example.txt"
                },
                "size": {
                    "description": "文件大小(字节)",
                    "type": "integer",
                    "example": 1024000
                },
                "task_id": {
                    "description": "任务ID",
                    "type": "string",
                    "example": "task_123456789"
                },
                "upload_at": {
                    "description": "上传时间",
                    "type": "string",
                    "example": "2024-01-01T00:00:00Z"
                }
            }
        },
        "models.User": {
            "type": "object",
            "properties": {
                "created_at": {
                    "type": "string"
                },
                "email": {
                    "type": "string"
                },
                "id": {
                    "type": "integer"
                },
                "is_active": {
                    "type": "boolean"
                },
                "last_login": {
                    "type": "string"
                },
                "role": {
                    "type": "string"
                },
                "updated_at": {
                    "type": "string"
                },
                "username": {
                    "type": "string"
                }
            }
        },
        "models.UserProfile": {
            "type": "object",
            "properties": {
                "created_at": {
                    "type": "string"
                },
                "email": {
                    "type": "string"
                },
                "id": {
                    "type": "integer"
                },
                "is_active": {
                    "type": "boolean"
                },
                "last_login": {
                    "type": "string"
                },
                "role": {
                    "type": "string"
                },
                "username": {
                    "type": "string"
                }
            }
        }
    }
}`

// SwaggerInfo holds exported Swagger Info so clients can modify it
var SwaggerInfo = &swag.Spec{
	Version:          "1.0",
	Host:             "localhost:8080",
	BasePath:         "/api",
	Schemes:          []string{},
	Title:            "Ebook Generator API",
	Description:      "电子书转换服务API",
	InfoInstanceName: "swagger",
	SwaggerTemplate:  docTemplate,
	LeftDelim:        "{{",
	RightDelim:       "}}",
}

func init() {
	swag.Register(SwaggerInfo.InstanceName(), SwaggerInfo)
}
