// Package docs Code generated by swaggo/swag. DO NOT EDIT
package docs

import "github.com/swaggo/swag"

const docTemplate = `{
    "schemes": {{ marshal .Schemes }},
    "swagger": "2.0",
    "info": {
        "description": "{{escape .Description}}",
        "title": "{{.Title}}",
        "termsOfService": "http://swagger.io/terms/",
        "contact": {
            "name": "API Support",
            "url": "http://www.swagger.io/support",
            "email": "support@swagger.io"
        },
        "license": {
            "name": "Apache 2.0",
            "url": "http://www.apache.org/licenses/LICENSE-2.0.html"
        },
        "version": "{{.Version}}"
    },
    "host": "{{.Host}}",
    "basePath": "{{.BasePath}}",
    "paths": {
        "/cleanup/{taskId}": {
            "delete": {
                "description": "清理任务相关的所有文件",
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "任务管理"
                ],
                "summary": "清理任务文件",
                "parameters": [
                    {
                        "type": "string",
                        "description": "任务ID",
                        "name": "taskId",
                        "in": "path",
                        "required": true
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "allOf": [
                                {
                                    "$ref": "#/definitions/models.APIResponse"
                                },
                                {
                                    "type": "object",
                                    "properties": {
                                        "data": {
                                            "$ref": "#/definitions/models.CleanupResponse"
                                        }
                                    }
                                }
                            ]
                        }
                    },
                    "404": {
                        "description": "Not Found",
                        "schema": {
                            "$ref": "#/definitions/models.APIResponse"
                        }
                    },
                    "500": {
                        "description": "Internal Server Error",
                        "schema": {
                            "$ref": "#/definitions/models.APIResponse"
                        }
                    }
                }
            }
        },
        "/convert": {
            "post": {
                "description": "开始将txt文件转换为电子书",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "转换管理"
                ],
                "summary": "开始电子书转换",
                "parameters": [
                    {
                        "description": "转换参数",
                        "name": "request",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/models.ConvertRequest"
                        }
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "allOf": [
                                {
                                    "$ref": "#/definitions/models.APIResponse"
                                },
                                {
                                    "type": "object",
                                    "properties": {
                                        "data": {
                                            "$ref": "#/definitions/models.ConvertResponse"
                                        }
                                    }
                                }
                            ]
                        }
                    },
                    "400": {
                        "description": "Bad Request",
                        "schema": {
                            "$ref": "#/definitions/models.APIResponse"
                        }
                    },
                    "500": {
                        "description": "Internal Server Error",
                        "schema": {
                            "$ref": "#/definitions/models.APIResponse"
                        }
                    }
                }
            }
        },
        "/download/{fileId}": {
            "get": {
                "description": "下载转换后的电子书文件",
                "produces": [
                    "application/octet-stream"
                ],
                "tags": [
                    "文件管理"
                ],
                "summary": "下载电子书文件",
                "parameters": [
                    {
                        "type": "string",
                        "description": "文件ID",
                        "name": "fileId",
                        "in": "path",
                        "required": true
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "type": "file"
                        }
                    },
                    "404": {
                        "description": "Not Found",
                        "schema": {
                            "$ref": "#/definitions/models.APIResponse"
                        }
                    },
                    "500": {
                        "description": "Internal Server Error",
                        "schema": {
                            "$ref": "#/definitions/models.APIResponse"
                        }
                    }
                }
            }
        },
        "/events/{taskId}": {
            "get": {
                "description": "通过SSE获取任务的实时事件流",
                "produces": [
                    "text/event-stream"
                ],
                "tags": [
                    "转换管理"
                ],
                "summary": "获取任务事件流",
                "parameters": [
                    {
                        "type": "string",
                        "description": "任务ID",
                        "name": "taskId",
                        "in": "path",
                        "required": true
                    }
                ],
                "responses": {
                    "200": {
                        "description": "SSE事件流",
                        "schema": {
                            "type": "string"
                        }
                    },
                    "404": {
                        "description": "Not Found",
                        "schema": {
                            "$ref": "#/definitions/models.APIResponse"
                        }
                    }
                }
            }
        },
        "/status/{taskId}": {
            "get": {
                "description": "查询转换任务的当前状态",
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "转换管理"
                ],
                "summary": "查询转换状态",
                "parameters": [
                    {
                        "type": "string",
                        "description": "任务ID",
                        "name": "taskId",
                        "in": "path",
                        "required": true
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "allOf": [
                                {
                                    "$ref": "#/definitions/models.APIResponse"
                                },
                                {
                                    "type": "object",
                                    "properties": {
                                        "data": {
                                            "$ref": "#/definitions/models.TaskStatusResponse"
                                        }
                                    }
                                }
                            ]
                        }
                    },
                    "404": {
                        "description": "Not Found",
                        "schema": {
                            "$ref": "#/definitions/models.APIResponse"
                        }
                    },
                    "500": {
                        "description": "Internal Server Error",
                        "schema": {
                            "$ref": "#/definitions/models.APIResponse"
                        }
                    }
                }
            }
        },
        "/upload": {
            "post": {
                "description": "上传txt文件用于转换",
                "consumes": [
                    "multipart/form-data"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "文件管理"
                ],
                "summary": "上传txt文件",
                "parameters": [
                    {
                        "type": "file",
                        "description": "txt文件",
                        "name": "file",
                        "in": "formData",
                        "required": true
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "allOf": [
                                {
                                    "$ref": "#/definitions/models.APIResponse"
                                },
                                {
                                    "type": "object",
                                    "properties": {
                                        "data": {
                                            "$ref": "#/definitions/models.UploadResponse"
                                        }
                                    }
                                }
                            ]
                        }
                    },
                    "400": {
                        "description": "Bad Request",
                        "schema": {
                            "$ref": "#/definitions/models.APIResponse"
                        }
                    },
                    "500": {
                        "description": "Internal Server Error",
                        "schema": {
                            "$ref": "#/definitions/models.APIResponse"
                        }
                    }
                }
            }
        }
    },
    "definitions": {
        "models.APIResponse": {
            "type": "object",
            "properties": {
                "code": {
                    "description": "状态码",
                    "type": "integer",
                    "example": 200
                },
                "data": {
                    "description": "数据"
                },
                "error": {
                    "description": "错误信息",
                    "type": "string",
                    "example": ""
                },
                "message": {
                    "description": "消息",
                    "type": "string",
                    "example": "success"
                }
            }
        },
        "models.CleanupResponse": {
            "type": "object",
            "properties": {
                "cleaned": {
                    "description": "是否清理成功",
                    "type": "boolean",
                    "example": true
                },
                "cleaned_at": {
                    "description": "清理时间",
                    "type": "string",
                    "example": "2024-01-01T00:10:00Z"
                },
                "cleaned_files": {
                    "description": "已清理的文件列表",
                    "type": "array",
                    "items": {
                        "type": "string"
                    }
                },
                "message": {
                    "description": "消息",
                    "type": "string",
                    "example": "清理完成"
                },
                "task_id": {
                    "description": "任务ID",
                    "type": "string",
                    "example": "task_123456789"
                }
            }
        },
        "models.ConvertRequest": {
            "type": "object",
            "required": [
                "bookname",
                "format",
                "task_id"
            ],
            "properties": {
                "align": {
                    "description": "标题对齐方式",
                    "type": "string",
                    "example": "center"
                },
                "author": {
                    "description": "作者",
                    "type": "string",
                    "example": "作者名"
                },
                "bookname": {
                    "description": "书名",
                    "type": "string",
                    "example": "示例小说"
                },
                "bottom": {
                    "description": "段落间距",
                    "type": "string",
                    "example": "1em"
                },
                "cover": {
                    "description": "封面设置",
                    "type": "string",
                    "example": "gen"
                },
                "cover_orly_color": {
                    "description": "封面颜色",
                    "type": "string",
                    "example": "#FF6B6B"
                },
                "cover_orly_idx": {
                    "description": "封面动物索引",
                    "type": "integer",
                    "example": 1
                },
                "exclusion_pattern": {
                    "description": "排除规则",
                    "type": "string",
                    "example": "^第[0-9一二三四五六七八九十零〇百千两 ]+(部门|部队)"
                },
                "font": {
                    "description": "嵌入字体",
                    "type": "string",
                    "example": ""
                },
                "format": {
                    "description": "输出格式",
                    "type": "string",
                    "enum": [
                        "epub",
                        "mobi",
                        "azw3",
                        "all"
                    ],
                    "example": "epub"
                },
                "indent": {
                    "description": "段落缩进",
                    "type": "integer",
                    "example": 2
                },
                "lang": {
                    "description": "语言设置",
                    "type": "string",
                    "example": "zh"
                },
                "line_height": {
                    "description": "行高",
                    "type": "string",
                    "example": "1.5"
                },
                "match": {
                    "description": "章节匹配规则",
                    "type": "string",
                    "example": "^第[0-9一二三四五六七八九十零〇百千两 ]+[章回节集幕卷部]"
                },
                "max": {
                    "description": "标题最大字数",
                    "type": "integer",
                    "example": 35
                },
                "task_id": {
                    "description": "任务ID",
                    "type": "string",
                    "example": "task_123456789"
                },
                "tips": {
                    "description": "是否添加教程文本",
                    "type": "boolean",
                    "example": true
                },
                "unknow_title": {
                    "description": "未知章节名称",
                    "type": "string",
                    "example": "章节正文"
                },
                "volume_match": {
                    "description": "卷匹配规则",
                    "type": "string",
                    "example": "^第[0-9一二三四五六七八九十零〇百千两 ]+[卷部]"
                }
            }
        },
        "models.ConvertResponse": {
            "type": "object",
            "properties": {
                "message": {
                    "description": "消息",
                    "type": "string",
                    "example": "转换任务已开始"
                },
                "started_at": {
                    "description": "开始时间",
                    "type": "string",
                    "example": "2024-01-01T00:00:00Z"
                },
                "status": {
                    "description": "状态",
                    "type": "string",
                    "example": "processing"
                },
                "task_id": {
                    "description": "任务ID",
                    "type": "string",
                    "example": "task_123456789"
                }
            }
        },
        "models.ConvertedFile": {
            "type": "object",
            "properties": {
                "file_id": {
                    "description": "文件ID",
                    "type": "string",
                    "example": "file_123456789"
                },
                "filename": {
                    "description": "文件名",
                    "type": "string",
                    "example": "example.epub"
                },
                "format": {
                    "description": "格式",
                    "type": "string",
                    "example": "epub"
                },
                "path": {
                    "description": "文件路径(内部使用)",
                    "type": "string"
                },
                "size": {
                    "description": "文件大小(字节)",
                    "type": "integer",
                    "example": 2048000
                }
            }
        },
        "models.TaskStatusResponse": {
            "type": "object",
            "properties": {
                "completed_at": {
                    "description": "完成时间",
                    "type": "string",
                    "example": "2024-01-01T00:05:00Z"
                },
                "error": {
                    "description": "错误信息",
                    "type": "string",
                    "example": ""
                },
                "files": {
                    "description": "转换后的文件列表",
                    "type": "array",
                    "items": {
                        "$ref": "#/definitions/models.ConvertedFile"
                    }
                },
                "logs": {
                    "description": "处理日志",
                    "type": "array",
                    "items": {
                        "type": "string"
                    }
                },
                "message": {
                    "description": "当前状态消息",
                    "type": "string",
                    "example": "转换完成"
                },
                "metadata": {
                    "description": "元数据",
                    "type": "object",
                    "additionalProperties": true
                },
                "progress": {
                    "description": "进度百分比",
                    "type": "integer",
                    "example": 100
                },
                "started_at": {
                    "description": "开始时间",
                    "type": "string",
                    "example": "2024-01-01T00:00:00Z"
                },
                "status": {
                    "description": "状态",
                    "type": "string",
                    "example": "completed"
                },
                "task_id": {
                    "description": "任务ID",
                    "type": "string",
                    "example": "task_123456789"
                }
            }
        },
        "models.UploadResponse": {
            "type": "object",
            "properties": {
                "filename": {
                    "description": "文件名",
                    "type": "string",
                    "example": "example.txt"
                },
                "size": {
                    "description": "文件大小(字节)",
                    "type": "integer",
                    "example": 1024000
                },
                "task_id": {
                    "description": "任务ID",
                    "type": "string",
                    "example": "task_123456789"
                },
                "upload_at": {
                    "description": "上传时间",
                    "type": "string",
                    "example": "2024-01-01T00:00:00Z"
                }
            }
        }
    }
}`

// SwaggerInfo holds exported Swagger Info so clients can modify it
var SwaggerInfo = &swag.Spec{
	Version:          "1.0",
	Host:             "localhost:8080",
	BasePath:         "/api",
	Schemes:          []string{},
	Title:            "Ebook Generator API",
	Description:      "电子书转换服务API",
	InfoInstanceName: "swagger",
	SwaggerTemplate:  docTemplate,
	LeftDelim:        "{{",
	RightDelim:       "}}",
}

func init() {
	swag.Register(SwaggerInfo.InstanceName(), SwaggerInfo)
}
